name: Sunbird-content-player-functional-test
on:
    push:
      branches:
      - release-2.9.0-functionalTest
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install player dependencies 
      run: |
        (cd player && npm install && npm install -g forever)

    - name: Build player preview
      run: |
        (cd player && npm run package-coreplugins -- --env.channel=sunbird && npm run build-preview sunbird)

    - name: Start player with fixture stories 
      run: |
        (cd player && forever start app.js)

    - name: Install test cases dependencies
      run: |
        (cd player/public/test && yarn install)  

    - name: Start function test cases 
      run: |
        (cd player/public/test && yarn test)
 
    - name: Visual changes on UI artifact generation
      uses: actions/upload-artifact@v1
      with:
        name: Visual changes on UI
        path: player/public/test/__tests__/__image_snapshots__

    - name: Screenshots artifact generation
      uses: actions/upload-artifact@v1
      with:
        name: Screenshots
        path: player/public/test/__tests__/screenshots

    - name: Report artifact generation
      uses: actions/upload-artifact@v1
      with:
        name: Report HTML
        path: player/public/test/testReport

    - name: Player preview artifact generation
      uses: actions/upload-artifact@v1
      with:
        name: Generated Player preview
        path: player/www

      env:
        CI: true
        