name: Node.js CI
on:
    push:
      branches:
      - release-2.9.0-functionalTest
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: (cd player && npm install && npm install -g forever)
    - run: (cd player && forever start app.js)
    - run: (cd player/public/test && yarn install)
    - run: (cd player/public/test && yarn test __tests__/questionset.js)
      env:
        CI: true
        