name: Node.js CI

on:
    push:
      branches:
      - release-2.9.0-functionalTest

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: (cd /home/runner/work/sunbird-content-player/sunbird-content-player/player && npm install)
    - run: (cd /home/runner/work/sunbird-content-player/sunbird-content-player/player && node app)
    - run: (cd /home/runner/work/sunbird-content-player/sunbird-content-player/player/public/test && yarn install)
    - run: (cd /home/runner/work/sunbird-content-player/sunbird-content-player/player/public/test && yarn test)
      env:
        CI: true

